# Generated by Django 5.0.4 on 2024-05-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.CharField(max_length=8)),
                ('edad_paciente', models.IntegerField(default=0)),
                ('rpm_paciente', models.IntegerField(default=0)),
                ('temp_paciente', models.IntegerField(default=0)),
                ('pulse_paciente', models.IntegerField(default=0)),
                ('pres_paciente', models.IntegerField(default=0)),
            ],
        ),
    ]
