# Generated by Django 5.0.4 on 2024-06-04 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_datosmodel_sex_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmodel',
            name='edad_paciente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AlterField(
            model_name='datosmodel',
            name='pres_paciente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AlterField(
            model_name='datosmodel',
            name='pulse_paciente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='datosmodel',
            name='rpm_paciente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='datosmodel',
            name='temp_paciente',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(33), django.core.validators.MaxValueValidator(43)]),
        ),
    ]
